import SearchBar from "../../components/client/search-bar";
import React from "react";
import HeaderBar from "../../components/server/header-bar";
import {AuthService} from "../../lib/services/authService";

export const metadata = {
  title: 'SIVTER',
  description: 'Generated by Next.js',
}

export default async function AuthLayout({children}: { children: React.ReactNode }) {
    const { isLoggedIn, userData } = (await AuthService.getAuthState());

    return (
        <>
            <div className="col-start-1 col-end-3 row-start-1 z-10 bg-transparent">
                <HeaderBar isLoggedIn={isLoggedIn} userData={userData}/>
            </div>
            <div className="col-start-1 col-end-3 row-start-2 z-10 bg-transparent">
                <SearchBar/>
            </div>
            <div className="col-start-1 col-end-3 row-start-3 z-10 bg-transparent overflow-y-auto no-scrollbar scroll-smooth">
                {children}
            </div>
        </>
    )
}
