import HeaderBar from "../../components/server/header-bar";
import UserNavigation from "../../components/client/user-navigation";
import SearchBar from "../../components/client/search-bar";
import Footer from "../../components/server/footer";
import React from "react";

export const metadata = {
    title: 'Layout Template',
    description: 'Generated by Next.js',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <head>
            <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0"/>
            <link rel="preconnect" href="https://fonts.googleapis.com"/>
            <link rel="preconnect" href="https://fonts.gstatic.com"/>
            <link href="https://fonts.googleapis.com/css2?family=VT323&display=swap" rel="stylesheet"/>
            <link href="https://fonts.googleapis.com/css2?family=Michroma&display=swap" rel="stylesheet"/>
            <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet"/>
        </head>
        <body className="bg-custom-gradient w-screen h-screen">
        <div className="container grid grid-cols-layout grid-rows-layout w-screen max-w-[1920px]">
            <div className="header relative col-span-2 z-10 bg-transparent">
                <HeaderBar/>
            </div>
            <div className="search relative col-span-2 z-10 bg-transparent">
                <SearchBar/>
            </div>
            <div className="navigation relative col-span-1 row-start-3 z-10 bg-transparent">
                <UserNavigation/>
            </div>
            <div className="main-content flex flex-row col-span-1 col-start-2 row-start-3 z-0 overflow-hidden">
                {children}
            </div>
        </div>
        </body>
        </html>
    )
}
