import HeaderBar from "../../components/server/header-bar";
import UserNavigation from "../../components/client/user-navigation";
import SearchBar from "../../components/client/search-bar";
import Footer from "../../components/server/footer";
import React from "react";

export const metadata = {
    title: 'Layout Template',
    description: 'Generated by Next.js',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <div className="container grid grid-cols-layout grid-rows-layout w-screen max-w-[1920px]">
            <div className="header relative col-span-2 z-10 bg-transparent">
                <HeaderBar/>
            </div>
            <div className="search relative col-span-2 z-10 bg-transparent">
                <SearchBar/>
            </div>
            <div className="navigation relative col-span-1 row-start-3 z-10 bg-transparent">
                <UserNavigation/>
            </div>
            <div className="main-content flex col-span-1 col-start-2 row-start-3 z-0 overflow-auto no-scrollbar mr-4">
                {children}
            </div>
        </div>
    )
}
