import HeaderBar from "../../../components/server/header-bar";
import SearchBar from "../../../components/client/search-bar";
import React from "react";
import AccountNavigation from "../../../components/client/account-navigation";
import {AuthService} from "../../../lib/services/authService";

export const metadata = {
    title: 'Layout Template',
    description: 'Generated by Next.js',
}

export default async function RootLayout({children}: { children: React.ReactNode }) {
    const {isLoggedIn, userData} = await AuthService.getAuthState();

    return (
        <div className="container grid grid-cols-layout grid-rows-layout w-screen max-w-[1920px]">
            <div className="header relative col-span-2 z-10 bg-transparent">
                <HeaderBar isLoggedIn={isLoggedIn} userData={userData}/>
            </div>
            <div className="search relative col-span-2 z-10 bg-transparent">
                <SearchBar/>
            </div>
            <div className="navigation relative col-span-1 row-start-3 z-10 bg-transparent">
                <AccountNavigation/>
            </div>
            <div
                className="main-content w-full h-full col-span-1 col-start-2 row-start-3 z-0 overflow-auto no-scrollbar">
                {children}
            </div>
        </div>
    )
}
