import React from "react";
import HeaderBar from "../components/server/header-bar";
import SearchBar from "../components/client/search-bar";
import UserNavigation from "../components/client/user-navigation";
import {cookies} from "next/headers";
import {verify} from "jsonwebtoken";

export const metadata = {
  title: 'Layout Template',
  description: 'Generated by Next.js',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

    const cookieStore = await cookies();
    const token = cookieStore.get('token')?.value;

    let isLoggedIn = false;
    let userData = null;

    if (token) {
        try {
            userData = verify(token, `${process.env.JWT_SECRET}`) as { username: string, userid: number };

            // if decode successful
            if (userData.username) {
                isLoggedIn = true;
            }
        } catch (error) {
            console.log(error);
        }
    }

    return (
        <html lang="en">
        <head>
            <link rel="stylesheet"
                  href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0"/>
            <link rel="preconnect" href="https://fonts.googleapis.com"/>
            <link rel="preconnect" href="https://fonts.gstatic.com"/>
            <link href="https://fonts.googleapis.com/css2?family=VT323&display=swap" rel="stylesheet"/>
            <link href="https://fonts.googleapis.com/css2?family=Michroma&display=swap" rel="stylesheet"/>
            <link rel="stylesheet"
                  href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200"/>
            <link rel="stylesheet"
                  href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200"/>
            <link rel="stylesheet"
                  href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200"/>
            <link
                href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
                rel="stylesheet"/>
            <title></title>
        </head>
        <body className="flex justify-center bg-custom-gradient w-screen">
        <div className="container grid grid-cols-layout grid-rows-layout w-screen max-w-[1920px] pb-0 pl-6">
            <div className="header relative col-span-2 z-10 bg-transparent">
                <HeaderBar isLoggedIn={isLoggedIn} userData={userData}/>
            </div>
            <div className="search relative col-span-2 z-10 bg-transparent">
                <SearchBar/>
            </div>
            <div className="navigation relative col-span-1 row-start-3 z-10 bg-transparent">
                <UserNavigation/>
            </div>
            {children}
        </div>
        </body>
        </html>
    )
}
