import React from "react";
import HeaderBar from "../components/server/header-bar";
import SearchBar from "../components/client/search-bar";
import UserNavigation from "../components/client/user-navigation";
import {AuthService} from "../lib/services/authService";


export const metadata = {
  title: 'Layout Template',
  description: 'Generated by Next.js',
}

export default async function RootLayout({children}: { children: React.ReactNode }) {

    const { isLoggedIn, userData } = (await AuthService.getAuthState());

    return (
        <html lang="en">
        <head>
            <link rel="stylesheet"
                  href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0"/>
            <link rel="preconnect" href="https://fonts.googleapis.com"/>
            <link rel="preconnect" href="https://fonts.gstatic.com"/>
            <link href="https://fonts.googleapis.com/css2?family=VT323&display=swap" rel="stylesheet"/>
            <link href="https://fonts.googleapis.com/css2?family=Michroma&display=swap" rel="stylesheet"/>
            <link rel="stylesheet"
                  href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200"/>
            <link rel="stylesheet"
                  href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200"/>
            <link rel="stylesheet"
                  href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200"/>
            <link
                href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
                rel="stylesheet"/>
            <title></title>
        </head>
        <body className="flex justify-center bg-custom-gradient min-h-screen w-screen">
        <div className="grid grid-cols-[auto_1fr] grid-rows-[auto_auto_1fr] w-screen max-h-screen max-w-[1920px] pl-6">
            <div className="col-start-1 col-end-3 row-start-1 z-10 bg-transparent">
                <HeaderBar isLoggedIn={isLoggedIn} userData={userData}/>
            </div>
            <div className="col-start-1 col-end-3 row-start-2 z-10 bg-transparent">
                <SearchBar/>
            </div>
            <div className="col-start-1 col-end-2 row-start-3 z-10 bg-transparent">
                <UserNavigation/>
            </div>
            <div className="col-start-2 col-end-3 row-start-3 z-10 bg-transparent overflow-y-auto no-scrollbar scroll-smooth">
                {children}
            </div>
        </div>
        </body>
        </html>
    )
}
