import Header from "../components/header";
import Navigation from "../components/navigation";

export const metadata = {
  title: 'Layout Template',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html className="bg-midnight" lang="en" >
        <body className="bg-midnight">
          <div className="header-wrapper fixed">
            <Header />
          </div>
          <div className="nav-wrapper fixed">
            <div className="nav-spacer h-[64px] w-[255px]"></div>
            <Navigation/>
          </div>
          {children}
        </body>
    </html>
  )
}
